---
swagger: "2.0"
info:
  title: RMC API edited [test edit]
  version: 1.0.0
  description: |
    ### Authorization

    Authorization: Bearer `<token>`
host: unmt6enx6c.execute-api.us-east-1.amazonaws.com
basePath: /dev/v1
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /register:
    post:
      tags:
      - Registration
      parameters:
      - name: code
        schema:
          type: object
          properties:
            code:
              type: string
        in: body
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              token:
                type: string
              user:
                $ref: '#/definitions/user'
      summary: Register/Authorize with FB Account Kit verification code
  /numbers:
    get:
      tags:
      - Service numbers
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              numbers:
                type: array
                items:
                  $ref: '#/definitions/number'
              recommended:
                type: array
                items:
                  $ref: '#/definitions/number'
      summary: Get list of servicenumbers
  /subscription:
    post:
      tags:
      - Subscriptions
      parameters:
      - name: receipt
        schema:
          type: object
          properties:
            receipt:
              type: string
        in: body
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              user:
                $ref: '#/definitions/user'
      summary: Verify receipt and update user status
  /records:
    post:
      tags:
      - Records
      parameters:
      - name: params
        schema:
          $ref: '#/definitions/paging'
        in: body
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              records:
                type: array
                items:
                  $ref: '#/definitions/record'
      summary: Get list of user records
  /records/{recordId}:
    get:
      tags:
      - Records
      parameters:
      - name: recordId
        description: Record ID of the record to get
        in: path
        required: true
        type: string
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              record:
                $ref: '#/definitions/record'
      summary: Get record by id
  /records/{recordId}/update:
    post:
      tags:
      - Records
      parameters:
      - name: recordId
        in: path
        required: true
        type: string
      - name: params
        schema:
          type: object
          properties:
            title:
              type: string
        in: body
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              record:
                $ref: '#/definitions/record'
      summary: Update record title by id
  /records/{recordId}/delete:
    post:
      tags:
      - Records
      parameters:
      - name: recordId
        in: path
        required: true
        type: string
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              record:
                $ref: '#/definitions/record'
      summary: Delete record by id
  /records/{recordId}/restore:
    post:
      tags:
      - Records
      parameters:
      - name: recordId
        in: path
        required: true
        type: string
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              record:
                $ref: '#/definitions/record'
      summary: Restore deleted record by id
  /records/{recordId}/read:
    post:
      tags:
      - Records
      parameters:
      - name: recordId
        in: path
        required: true
        type: string
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              record:
                $ref: '#/definitions/record'
      summary: Mark as read record by id
  /search:
    post:
      tags:
      - Records
      - Search
      parameters:
      - name: params
        schema:
          $ref: '#/definitions/search'
        in: body
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              records:
                type: array
                items:
                  $ref: '#/definitions/record'
      summary: Search user records
  /phonenumber:
    post:
      tags:
      - Number
      - User
      parameters:
      - name: code
        schema:
          type: object
          properties:
            code:
              type: string
        in: body
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              token:
                type: string
              user:
                $ref: '#/definitions/user'
        "422":
          description: Fail (phone mumber already used)
          schema:
            type: object
            properties:
              error:
                type: string
      summary: Edit own number with FB Account Kit verification code
  /deactivate:
    post:
      tags:
      - Users
      responses:
        "200":
          description: Success
      summary: Delete account with all data
  /call:
    post:
      tags:
      - Calls
      parameters:
      - name: phoneNumber
        schema:
          type: object
          properties:
            phoneNumber:
              type: string
        in: body
      responses:
        "200":
          description: Success
      summary: Search user records
  /me:
    get:
      tags:
      - User
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              user:
                $ref: '#/definitions/user'
      summary: Get authorized user info
definitions:
  user:
    type: object
    properties:
      userId:
        type: string
      phoneNumber:
        type: string
      serviceNumber:
        type: object
        properties:
          country:
            type: string
          phoneNumber:
            type: string
          flag:
            type: string
      subscriptionStatus:
        enum:
        - none
        - active
        - expired
        type: string
  number:
    type: object
    properties:
      country:
        type: string
      number:
        type: string
      flag:
        type: string
  record:
    type: object
    properties:
      recordId:
        type: string
      time:
        type: integer
      duration:
        type: integer
      status:
        enum:
        - pending
        - new
        - read
        type: string
      phoneNumber:
        type: string
      title:
        type: string
      link:
        type: string
      waveLink:
        type: string
  paging:
    type: object
    properties:
      beforeId:
        type: string
      afterId:
        type: string
      count:
        type: integer
  search:
    type: object
    properties:
      beforeId:
        type: string
      afterId:
        type: string
      count:
        type: integer
      query:
        type: string
      phoneNumbers:
        type: array
        items:
          type: string
securityDefinitions:
  API Key - 1:
    type: apiKey
    name: API Key
    in: query
